name: Matrix Build (All Configs)

on:
  workflow_dispatch:

jobs:
  call-template:
    strategy:
      matrix:
        router_config:
          - asus_rt-n11p-a1_stable.config
          - asus_rt-n11p-a1_new.config
          - asus_rt-n11p-b1_stable.config
          - tplink_wr841n-v13.config
          - tplink_wr841n-v13_usb.config
          - tplink_wr841n-v14.config
          - tplink_wr841n-v14_8m.config
      fail-fast: false
    
    uses: ./.github/workflows/_build-template.yml
    with:
      config_file: ${{ matrix.router_config }}